import { createFileRoute } from "@tanstack/react-router";
import { Card } from "@heroui/react";
import { useQuery } from "@tanstack/react-query";
import { apiUrl } from "../../lib/api/client";

export const Route = createFileRoute("/_authenticated/analytics")({
  component: AnalyticsPage
});

type Alert = {
  id: string;
  branchId: string | null;
  machineId: string | null;
  ruleId: string | null;
  severity: string;
  title: string;
  detail: string | null;
  tags: string[];
  detectedAt: string;
  acknowledgedAt: string | null;
  acknowledgedLocally?: boolean;
};

function fmtTime(iso: string): string {
  return new Date(iso).toLocaleString("th-TH", {
    day: "2-digit",
    month: "2-digit",
    hour: "2-digit",
    minute: "2-digit"
  });
}

function severityClass(severity: string): string {
  const s = severity.toLowerCase();
  if (s.includes("critical") || s.includes("high")) return "bg-danger/15 text-danger";
  if (s.includes("warn") || s.includes("medium")) return "bg-warning/15 text-warning";
  return "bg-default-100 text-default-500";
}

function AnalyticsPage() {
  const summaryQuery = useQuery({
    queryKey: ["report", "summary"],
    queryFn: async () => {
      const res = await fetch(apiUrl("/api/report/summary"), { credentials: "include" });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = (await res.json()) as { summary: string; generatedBy: string; generatedAt: string };
      return data;
    }
  });

  const alertsQuery = useQuery({
    queryKey: ["report", "alerts"],
    queryFn: async () => {
      const res = await fetch(apiUrl("/api/report/alerts"), { credentials: "include" });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = (await res.json()) as { alerts: { alerts: Alert[] } };
      return data.alerts.alerts;
    }
  });

  return (
    <div className="flex flex-col gap-6">
      <div>
        <h1 className="text-2xl font-bold">Analytics</h1>
        <p className="text-sm text-default-500">สรุปผู้บริหาร + แจ้งเตือน</p>
      </div>

      <Card>
        <div className="flex flex-col gap-2 p-4">
          <div className="flex items-center justify-between">
            <h2 className="font-semibold">สรุปผู้บริหาร (Executive Summary)</h2>
            {summaryQuery.data?.generatedBy && (
              <span className="text-xs text-default-400">generated by: {summaryQuery.data.generatedBy}</span>
            )}
          </div>
          {summaryQuery.isLoading && <p className="text-sm text-default-500">Loading…</p>}
          {summaryQuery.error && <p className="text-sm text-danger">{summaryQuery.error.message}</p>}
          {summaryQuery.data && <p className="text-sm leading-relaxed">{summaryQuery.data.summary}</p>}
        </div>
      </Card>

      <div>
        <h2 className="mb-2 text-lg font-semibold">การแจ้งเตือนล่าสุด</h2>
        {alertsQuery.isLoading && <p className="text-sm text-default-500">Loading…</p>}
        {alertsQuery.error && <p className="text-sm text-danger">{alertsQuery.error.message}</p>}
        {alertsQuery.data && alertsQuery.data.length === 0 && (
          <p className="text-sm text-default-400">ไม่มีการแจ้งเตือนในช่วงเวลาที่เลือก</p>
        )}
        <div className="flex flex-col gap-2">
          {alertsQuery.data?.map((alert) => (
            <Card key={alert.id}>
              <div className="flex items-start justify-between gap-3 p-4">
                <div className="flex flex-col gap-1">
                  <div className="flex items-center gap-2">
                    <span className={`rounded-full px-2 py-0.5 text-xs font-medium ${severityClass(alert.severity)}`}>
                      {alert.severity}
                    </span>
                    <strong className="text-sm">{alert.title}</strong>
                    {alert.acknowledgedLocally && (
                      <span className="rounded-full bg-success/15 px-2 py-0.5 text-xs text-success">acknowledged</span>
                    )}
                  </div>
                  {alert.detail && <p className="text-sm text-default-500">{alert.detail}</p>}
                  {alert.tags.length > 0 && (
                    <p className="text-xs text-default-400">#{alert.tags.join(" #")}</p>
                  )}
                </div>
                <span className="shrink-0 text-xs text-default-400">{fmtTime(alert.detectedAt)}</span>
              </div>
            </Card>
          ))}
        </div>
      </div>
    </div>
  );
}
